version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y git apache2

  pre_build:
    commands:
      - echo "Cloning the repository..."
      - git clone -b main https://github.com/krsna-kant/mark_ecommerce.git /tmp/mark_ecommerce

  build:
    commands:
      - echo "Deploying files to Apache..."
      - rm -rf /var/www/html/*
      - cp -r /tmp/mark_ecommerce/* /var/www/html/

  post_build:
    commands:
      - echo "Restarting Apache service..."
      - systemctl restart apache2
      - echo "Deployment completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
