version: 0.2

phases:
  install:
    commands:
      - echo "Installing Git and dependencies..."
      - yum install -y git
      - sudo yum install -y httpd  # Ensure Apache is installed

  pre_build:
    commands:
      - echo "Cloning the repository..."
      - git clone -b main https://github.com/krsna-kant/mark_ecommerce.git /tmp/mark_ecommerce

  build:
    commands:
      - echo "Deploying files to Apache..."
      - sudo rm -rf /var/www/html/*
      - sudo cp -r /tmp/mark_ecommerce/* /var/www/html/

  post_build:
    commands:
      - echo "Restarting Apache service..."
      - sudo systemctl restart httpd
      - echo "Deployment completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: yes

reports:
  email:
    files:
      - "**/*"
    base-directory: "/tmp/mark_ecommerce"
    discard-paths: yes

env:
  variables:
    DEPLOY_ENV: "production"

cache:
  paths:
    - '/tmp/mark_ecommerce/**/*'
